"""Updated Orders Table

Revision ID: 15d9ac9a5b1d
Revises: 6eb1b0a341da
Create Date: 2025-11-11 15:24:56.482855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d9ac9a5b1d'
down_revision = '6eb1b0a341da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('orders', 'qb_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('qb_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'supplier_id')
    # ### end Alembic commands ###
