"""Created Order_item table & updated transactions

Revision ID: 3164e93d4a09
Revises: 15d9ac9a5b1d
Create Date: 2025-11-12 09:13:46.491677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3164e93d4a09'
down_revision = '15d9ac9a5b1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('quantity_delta', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('state', sa.String(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'order_items', ['order_item_id'], ['id'])
    op.drop_column('transactions', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'state')
    op.drop_column('transactions', 'quantity_delta')
    op.drop_column('transactions', 'order_item_id')
    op.drop_table('order_items')
    # ### end Alembic commands ###
