"""Added Sections to Orders

Revision ID: 559643ea3200
Revises: 549a3ba079c3
Create Date: 2025-12-13 17:51:39.544555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559643ea3200'
down_revision = '549a3ba079c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'order_sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'section_id')
    op.drop_table('order_sections')
    # ### end Alembic commands ###
