"""checking

Revision ID: 616f14360892
Revises: add_blocked_items_table
Create Date: 2026-03-04 11:12:26.961212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616f14360892'
down_revision = 'add_blocked_items_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
