"""Start

Revision ID: 666853b4f3a8
Revises: 
Create Date: 2026-02-25 12:53:25.510590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666853b4f3a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_item_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stock_item_categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('air_filters', 'merv_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('air_filters', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('air_filters', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('air_filters', 'depth',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('air_filters', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_filters', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('air_filters', 'depth',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('air_filters', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('air_filters', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('air_filters', 'merv_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('stock_items')
    op.drop_table('stock_item_categories')
    # ### end Alembic commands ###
