"""empty message

Revision ID: 6e41176c60e1
Revises: 3164e93d4a09
Create Date: 2025-11-24 09:43:07.186926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e41176c60e1'
down_revision = '3164e93d4a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column(
    "products",
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    op.drop_constraint('quantities_product_id_fkey', 'quantities', type_='foreignkey')
    op.create_foreign_key(None, 'quantities', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_order_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_product_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_order_item_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_order_item_id_fkey', 'transactions', 'order_items', ['order_item_id'], ['id'])
    op.create_foreign_key('transactions_product_id_fkey', 'transactions', 'products', ['product_id'], ['id'])
    op.create_foreign_key('transactions_order_id_fkey', 'transactions', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'quantities', type_='foreignkey')
    op.create_foreign_key('quantities_product_id_fkey', 'quantities', 'products', ['product_id'], ['id'])
    op.drop_column('products', 'is_active')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
