"""Fixed relations and temporarly removed fluid filters

Revision ID: 6eb1b0a341da
Revises: c9a86474aec8
Create Date: 2025-11-11 08:34:44.235231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb1b0a341da'
down_revision = 'c9a86474aec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fluid_filters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fluid_filters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fluid_filters_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fluid_filters_pkey'),
    sa.UniqueConstraint('model_number', name='fluid_filters_model_number_key')
    )
    # ### end Alembic commands ###
