"""initial schema

Revision ID: 7b205737b53b
Revises: 
Create Date: 2025-10-15 20:01:35.847672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b205737b53b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('quantities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('ordered', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantities')
    op.drop_table('filters')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
