"""Removed non null constraint of order_number

Revision ID: 7fb5e69e8ec1
Revises: 93300b69f5a7
Create Date: 2025-12-18 09:12:00.272560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb5e69e8ec1'
down_revision = '93300b69f5a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
