"""changed airfitlers

Revision ID: 83a7105a3856
Revises: 6e41176c60e1
Create Date: 2025-12-10 15:24:12.840550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a7105a3856'
down_revision = '6e41176c60e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_filters', 'final_resistance')
    op.drop_column('air_filters', 'test_airflow_value')
    op.drop_column('air_filters', 'test_airflow_unit')
    op.drop_column('air_filters', 'initial_resistance')
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('air_filters', sa.Column('initial_resistance', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True))
    op.add_column('air_filters', sa.Column('test_airflow_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('air_filters', sa.Column('test_airflow_value', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('air_filters', sa.Column('final_resistance', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
