"""empty message

Revision ID: 88fc1e10983b
Revises: e90d0c5cb61d
Create Date: 2026-03-05 10:14:35.594602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fc1e10983b'
down_revision = 'e90d0c5cb61d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
