"""bye bye misc table

Revision ID: 8c76c242b57c
Revises: add_description_to_air_filters
Create Date: 2026-03-02 09:23:51.288847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c76c242b57c'
down_revision = 'add_description_to_air_filters'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('misc_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misc_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='misc_items_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='misc_items_pkey')
    )
    # ### end Alembic commands ###
