"""Added Sections

Revision ID: 90a9aefe44b1
Revises: 
Create Date: 2025-12-15 11:18:19.281227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a9aefe44b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'order_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'section_id')
    op.drop_table('order_sections')
    # ### end Alembic commands ###
