"""Updated Order

Revision ID: 93300b69f5a7
Revises: 94fd5fb54453
Create Date: 2025-12-18 08:39:06.449896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93300b69f5a7'
down_revision = '94fd5fb54453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.alter_column('order_sections', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('orders', sa.Column('external_order_number', sa.String(), nullable=True))
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_order_id', 'transactions', ['order_id'], unique=False)
    op.create_index('ix_transactions_order_item_id', 'transactions', ['order_item_id'], unique=False)
    op.create_index('ix_transactions_product_id', 'transactions', ['product_id'], unique=False)
    op.create_index('ix_transactions_state', 'transactions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_state', table_name='transactions')
    op.drop_index('ix_transactions_product_id', table_name='transactions')
    op.drop_index('ix_transactions_order_item_id', table_name='transactions')
    op.drop_index('ix_transactions_order_id', table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_column('orders', 'external_order_number')
    op.alter_column('order_sections', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('order_items', 'completion_date')
    # ### end Alembic commands ###
