"""Added eta to order table

Revision ID: 94fd5fb54453
Revises: 90a9aefe44b1
Create Date: 2025-12-16 13:20:43.278132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fd5fb54453'
down_revision = '90a9aefe44b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('eta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'eta')
    # ### end Alembic commands ###
