"""Add separator functionality to order items

Revision ID: add_separator_items
Revises: 97ed71639336
Create Date: 2026-01-28 20:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_separator_items'
down_revision = '97ed71639336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_separator column with default False
    op.add_column('order_items', sa.Column('is_separator', sa.Boolean(), nullable=False, server_default='0'))
    
    # Make product_id nullable
    op.alter_column('order_items', 'product_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    # Make quantity_ordered default to 0 for separator items
    op.alter_column('order_items', 'quantity_ordered',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server_default from quantity_ordered
    op.alter_column('order_items', 'quantity_ordered',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default=None)
    
    # Make product_id non-nullable again
    op.alter_column('order_items', 'product_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    
    # Drop is_separator column
    op.drop_column('order_items', 'is_separator')
    # ### end Alembic commands ###
