"""Add airflow and resistance fields to air_filters

Revision ID: c9a86474aec8
Revises: b9632317df33
Create Date: 2025-11-11 08:01:33.991873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a86474aec8'
down_revision = 'b9632317df33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_filters', sa.Column('initial_resistance', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('air_filters', sa.Column('final_resistance', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('air_filters', sa.Column('test_airflow_value', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('air_filters', sa.Column('test_airflow_unit', sa.String(length=10), nullable=True))
    op.drop_column('products', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('air_filters', 'test_airflow_unit')
    op.drop_column('air_filters', 'test_airflow_value')
    op.drop_column('air_filters', 'final_resistance')
    op.drop_column('air_filters', 'initial_resistance')
    # ### end Alembic commands ###
