"""Maybe

Revision ID: cfdbda715d15
Revises: 7fb5e69e8ec1
Create Date: 2025-12-18 12:45:30.839839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdbda715d15'
down_revision = '7fb5e69e8ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
