"""Added customers Table

Revision ID: ec580b9ec4cf
Revises: caa5be84f53e
Create Date: 2025-11-07 15:17:15.134314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec580b9ec4cf'
down_revision = 'caa5be84f53e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_table('customers')
    # ### end Alembic commands ###
