"""Added to_dict serialization for models

Revision ID: f8e3f34a984b
Revises: 7b205737b53b
Create Date: 2025-10-16 18:11:49.663856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e3f34a984b'
down_revision = '7b205737b53b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
